In [1]:
import torch
import numpy as np

In [2]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()

In [3]:
np_data

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
torch_data

tensor([[ 0,  1,  2],
        [ 3,  4,  5]])

In [5]:
tensor2array

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
print("\numpy array:\n", np_data,
     "\ntorch tensor:\n", torch_data,
     "\ntensor to array:\n", tensor2array)


umpy array:
 [[0 1 2]
 [3 4 5]] 
torch tensor:
 tensor([[ 0,  1,  2],
        [ 3,  4,  5]]) 
tensor to array:
 [[0 1 2]
 [3 4 5]]


In [9]:
data = [-1, -2, 1, 2]

In [10]:
tensor = torch.FloatTensor(data)

In [11]:
print("\nabs",
     "\nnumpy:", np.abs(data),
     "\ntorch:", torch.abs(tensor))


abs 
numpy: [1 2 1 2] 
torch: tensor([ 1.,  2.,  1.,  2.])


In [13]:
print("\nmean",
     "\nnumpy:", np.mean(data),
     "\ntorch:", torch.mean(tensor))


sin 
numpy: 0.0 
torch: tensor(0.)


In [14]:
print("\nsin",
     "\nnumpy:", np.sin(data),
     "\ntorch:", np.sin(tensor))


sin 
numpy: [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch: tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [15]:
# matrix multiplication
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)

In [17]:
print("\nmatrix multiplication (matmul)",
     "\nnumpy:\n", np.matmul(data, data),
     "\ntorch:\n", torch.mm(tensor, tensor))


matrix multiplication (matmul) 
numpy:
 [[ 7 10]
 [15 22]] 
torch:
 tensor([[  7.,  10.],
        [ 15.,  22.]])


In [18]:
# incorrect method
data = np.array(data)
print("\nmatrix multiplication (dot)",
     "\nnumpy:", data.dot(data),
     "\ntorch:", tensor.dot(tensor))

RuntimeError: Expected argument self to have 1 dimension, but has 2