In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad = True)

print(tensor)
print(variable)

tensor([[ 1.,  2.],
        [ 3.,  4.]])
tensor([[ 1.,  2.],
        [ 3.,  4.]])


In [3]:
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000)


In [4]:
v_out.backward()

In [5]:
variable.grad

tensor([[ 0.5000,  1.0000],
        [ 1.5000,  2.0000]])

In [6]:
variable.data

tensor([[ 1.,  2.],
        [ 3.,  4.]])

In [7]:
variable.data.numpy()

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)